version: '2.1'
services:
  mariadb:
    image: 'mariadb:10.5.8-focal'
    environment:
      - MYSQL_ROOT_PASSWORD=theVeryp@ssw0rd
      - MYSQL_DATABASE=pushdeer
    ports:
      - '3306:3306'
  redis:
    image: 'bitnami/redis:6.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
